### ISSUE TITLE
我的回帖

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/publish#44]
在 评论 组下面，增加我的回帖（论坛的）

- [x] 已完成

**Comment by Kaviilee** [comment]
## 统计接口
`https://next2.jx3box.com/api/my-resource/stat`需要新增帖子评论数  @flyflyknife 
<img width="1260" alt="image" src="https://github.com/JX3BOX/publish/assets/25825282/77dda034-aef9-489b-8ce1-39a0628b5347">

- [x] 已完成

**Comment by Kaviilee** [comment]
## 评论列表接口
如果可以希望新增`search`查询参数
接口`https://next2.jx3box.com/api/next2/community/discussion/my/comment/list`

- [x] 已完成

**Comment by Kaviilee** [comment]
## 我的回帖列表接口报错
<img width="1916" alt="image" src="https://github.com/JX3BOX/publish/assets/25825282/8a36bec9-bfbc-4b2f-a4f3-4112022d883d">

`/api/next2/community/discussion/my/reply/list?pageSize=10&index=1`

@flyflyknife 

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="885" alt="image" src="https://github.com/JX3BOX/publish/assets/8476969/a88ce25a-3553-4fac-97eb-14195bc488ee">

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="422" alt="image" src="https://github.com/JX3BOX/publish/assets/8476969/2f814f5d-c1d4-44ec-a105-3f00b47615dc">

- [x] 已完成

**Comment by iRuxu** [comment]
## 编辑回帖
<img width="1632" alt="image" src="https://github.com/JX3BOX/publish/assets/8476969/4d13aa81-da1f-4935-a69b-745366783bff">

可以用  /reply
帖子评论则不支持修改

但是楼层还是要支持修改，因为有些写小说的
权限，仅层主自己

@flyflyknife 

- [x] 已完成


---------------------
Reply:

 目前已有修改回帖的接口：

https://swagger.jx3box.com/swagger.html?urls.primaryName=next2.jx3box.com#/%E6%88%91%E7%9A%84-%E4%BA%A4%E6%B5%81%E8%AE%A8%E8%AE%BA-%E4%B8%BB%E9%A2%98%E5%B8%96-%E5%9B%9E%E8%B4%B4/Discussion_UpdateMyReply


可以根据回帖的作者id是否等于当前登录id 判定是否展示编辑按钮。

**Comment by iRuxu** [comment]
## 前台

<img width="1779" alt="image" src="https://github.com/JX3BOX/publish/assets/8476969/a9040cf1-d4e2-4f08-96a9-11cf13134798">

仅层主自己可见

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="623"  src="https://github.com/JX3BOX/publish/assets/8476969/b5b86966-e455-4918-ad3d-bfd0077336e6">

@flyflyknife 接口支持一下，联表返回对应信息

这里显示为  `回复:${原标题},${content}...`

content要去掉各种html标签，只取前12个字符，后面固定加`...`

- [x] 已完成

**Comment by iRuxu** [comment]
## 编辑详情
<img width="1284"  src="https://github.com/JX3BOX/publish/assets/8476969/3d82057f-9c76-426c-b95e-aadbdc98a7e2">

在回帖内容的上面加一行，RT

@flyflyknife 接口也支持一下，，联表返回对应信息

- [x] 已完成

**Comment by iRuxu** [comment]
## 编辑生成

<img width="999" alt="image" src="https://github.com/JX3BOX/publish/assets/8476969/27bf7dcd-e328-4d9c-b26e-ff8ad3cb8700">

我修改了ti帖子内容的

<img width="719" alt="image" src="https://github.com/JX3BOX/publish/assets/8476969/78d6c556-2c79-4b59-89a6-dc86d8e30551">

但是这个摘要并没有伴随改动。
而且内容也没有

@flyflyknife 前端确认是后端问题

- [x] 已完成

**Comment by iRuxu** [comment]
## 编辑无效

用户反馈，切换分类，实际上编辑不生效

@flyflyknife 

- [x] 已完成

**Comment by flyflyknife** [comment]
> ## 编辑无效
> 
> 用户反馈，切换分类，实际上编辑不生效
> 
> @flyflyknife
> 
>     * [ ]  已完成
详细列子，目前单元测试 修改分类是生效的

**Comment by iRuxu** [comment]
<img width="1437" alt="image" src="https://github.com/JX3BOX/publish/assets/8476969/b86cfa94-99a3-4ac4-b83d-eb7ed6bda6ae">
参考下bbs他列表页现在的过滤函数

- [x] 已完成

**Comment by iRuxu** [comment]
<img width="719" alt="image" src="https://github.com/JX3BOX/publish/assets/8476969/9c3a00fa-78db-4b03-ba90-e253b5695b9b">

- [x] 已完成

**Comment by iRuxu** [comment]
> ## 编辑详情
> <img alt="" width="1284" src="https://private-user-images.githubusercontent.com/8476969/332970552-3d82057f-9c76-426c-b95e-aadbdc98a7e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTk0ODYsIm5iZiI6MTcxNjg5OTE4NiwicGF0aCI6Ii84NDc2OTY5LzMzMjk3MDU1Mi0zZDgyMDU3Zi05Yzc2LTQyNmMtYjk1ZS1hYWRiZGM5OGE3ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMTIyNjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQ5M2UzMDlkOWRkYjRjNjliNWJkOWE1NTk2OGUxMTVhZDcxNzNhMjBmM2E0MGJmODg0NTY0ZDZiNzJkNzJiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3jK6nlCv_7oHadzvPbeFvf2fuZKaJevmQ5lVKMAKoS4">
> 在回帖内容的上面加一行，RT
> 
> @flyflyknife 接口也支持一下，，联表返回对应信息
> 
> * [x]  已完成

- [x] 已完成
