### ISSUE TITLE
创作中心——通识百科问题

### ISSUE THREAD

**Issue by yjrguxing** [JX3BOX/publish#7]
任意提交一条通识百科后
在怀旧服板块——创作中心——通识百科下无法查找到审核通过后的（所有）通识百科
在正式服板块下可以正常查看

问题建议：
1.可能为审核通识百科后存入数据库时默认为正式服，所以选择至怀旧服后无法查看
2.可能为怀旧服板块打开创作中心时查找的内容的服务器字段必须为怀旧服字段才会展示，但是由于通识百科不分正式服/怀旧服所以并未展示

**Comment by iRuxu** [comment]
@kuguats
