### ISSUE TITLE
移除宏的反馈

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/publish#8]
> 点击【移除本宏】按钮，每次都是删除的前一宏，而不是当前的宏

![image](https://user-images.githubusercontent.com/8476969/142395059-8f1b00a5-3f99-4754-b527-1c73c8b38320.png)

1.右下角的移除按钮，移除的索引不正确，需要修正

2.移除后，变更展示到一个有效索引；目前默认会空白

3.tab支持拖拽排序
![image](https://user-images.githubusercontent.com/8476969/142395307-0b3aa54c-203a-4e1b-9241-e8bd3e7870d3.png)

**Comment by Kaviilee** [comment]
@iRuxu 拖拽排序暂未实现
